# Generated by Django 5.1.2 on 2024-10-25 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='first_name',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='groups',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='is_active',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='is_staff',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='is_superuser',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='last_login',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='last_name',
        # ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='user_permissions',
        # ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.user'),
        ),
    ]
