# Generated by Django 5.1.2 on 2024-10-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_user_first_name_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
