# Generated by Django 5.1.2 on 2024-10-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
