# Generated by Django 5.1.2 on 2024-11-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blogpost_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
    ]
