# Generated by Django 5.1.2 on 2024-11-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_blogpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('Draft', 'Чернетка'), ('Published', 'Опубліковано')], default='Draft', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='blogpost',
            unique_together={('slug', 'published_at')},
        ),
    ]
