# Generated by Django 5.1.2 on 2024-11-07 12:10

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
   BlogPost = apps.get_model('blog_app', 'blogpost')
   for post in BlogPost.objects.all():
       post.slug = slugify(post.title)
       post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='empty-slug', unique_for_date=True),
            preserve_default=False,
        ),

        migrations.RunPython(populate_slugs),
    ]

